### PR TITLE
Fix is_service_exists for similarly named services

### LINKED ISSUE #14: Check for running service can match to similarly named services
The check for whether a service is running (`docker service ls -f name=some_service_name`) during up can erroneously match another service if the other service's name starts with the name of the service being checked.

E.g., if there is already a service named `example-web` and up checks for whether `example` is running, `docker service ls -f name=example | tail -n +2` matches on `example-web`, so `example` doesn't get started.

### PR DESCRIPTION
**Pull request by kinghuang**
Handle the case where the service being checked in is_service_exists is a substring of the name of an existing service. Compare the returned services and check for an exact match, instead of any match.

Resolves #14.

### CODE REVIEW

**Review by ddrozdov — COMMENTED** [review]
I guess it would be easier just to use `grep` and surround the name with the spaces, like this:

```
'docker service ls | grep " {} "'
```

**Comment by kinghuang** [comment]
I hadn't considered that! That does seem like a simpler option, and matches your original code better. I'll retract this pull request.

**Comment by ddrozdov** [comment]
To make it even more safe, we can do

```
'docker service ls | awk \'{{print $2}}\' | egrep "^{}$"'
```

**Comment by kinghuang** [comment]
Yup, that's a great way to match it. I've submitted #17 with it.

**Pull request closed without merging**
