### PR TITLE
Dockerfile: install bash

### PR DESCRIPTION
**Pull request by np**

### CODE REVIEW

**Comment by ddrozdov** [comment]
Why do you need bash in this container?

**Comment by np** [comment]
Sorry for the lack of explanations...

Here is the use of bash in the script: https://github.com/ddrozdov/docker-compose-swarm-mode/blob/master/docker_compose_swarm_mode.py#L76

**Comment by ddrozdov** [comment]
Oh, I see, I forgot about this change I've done :)

**Comment by cie** [comment]
Hi! Can you please release this change to Docker Hub?

By the way, thanks very much for this great software!

**Comment by ddrozdov** [comment]
Done. Version 2.1.0 has been released.

**Comment by cie** [comment]
thanks!

**Pull request merged**
